name: Process data
on:
  push:
    branches:
      - dev
      - master
      - prod
  workflow_dispatch:

jobs:
  process-card-data:
    runs-on: ubuntu-latest
    steps:
      - name: Push to bucket
        shell: bash
        run: |
          docker-compose build --pull app
          docker-compose run --rm --user "$(id -u)" app
          ./push.sh
      - name: Tear down Docker
        shell: bash
        run: docker-compose down
